name: Styleguide
logo: https://www.non.sa/www/img/logo-ar.svg

excludeDir:
  - docs

sidebar:
  background: "#dedad7"
  textColor: "#2a2a2a"

headHtml: |
  <link rel="stylesheet" href="dist/noon-uikit.min.css">